dev_db_host=dev-db.example.com
dev_db_user=dev_user
dev_db_pass=secret

uat_db_host=uat-db.example.com
uat_db_user=uat_user
uat_db_pass=secret

prod_db_host=prod-db.example.com
prod_db_user=prod_user
prod_db_pass=secret